# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import oracle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='E-mail Address')),
                ('status', models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('art_test_new', 'Art Test - New'), ('waiting_1st_feedback', 'Waiting for 1st feedback'), ('art_test_rejected', 'Art Test - Rejected'), ('art_test_kiv', 'Art Test - K.I.V'), ('waiting_2nd_feedback', 'Waiting for 2nd feedback'), ('rejected', 'Rejected'), ('rejected_kiv', 'Rejected - K.I.V'), ('offered', 'Offered')], default='new', max_length=30, verbose_name='Status :')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOriginated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=100, verbose_name='INTERVIEWER: ')),
                ('interview_date', models.DateField(default=datetime.date.today)),
                ('grooming', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Grooming')),
                ('body_language', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Body Language')),
                ('eye_contact', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Eye Contact')),
                ('confidence', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Confidence')),
                ('teamwork', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Teamwork')),
                ('responsible', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Responsible')),
                ('professional', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Professional/ Problem Solver')),
                ('communication', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Communication')),
                ('ability_to_learn', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Ability to Learn')),
                ('punctuality', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Punctuality')),
                ('qualification', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Education / Qualification')),
                ('skills', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Skills')),
                ('creativity', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Creativity')),
                ('knowledge_on_company', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Knowledge on Company')),
                ('knowledge_on_industry', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Knowledge on Industry')),
                ('evaluation', models.CharField(choices=[('unacceptable', 'Unacceptable'), ('average', 'Average'), ('acceptable', 'Acceptable')], default='', max_length=15, verbose_name='Evaluation')),
                ('comments', models.TextField(verbose_name='ADDITIONAL COMMENTS :')),
                ('feedback_time', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oracle.ApplicantList')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name (as in NRIC)')),
                ('nick_name', models.CharField(max_length=50, verbose_name='Nickname :')),
                ('applied_date', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(max_length=200, verbose_name='Current address :')),
                ('age', models.IntegerField(verbose_name='Age :')),
                ('photo', models.ImageField(upload_to=oracle.models.JobApplication.upload_photo_dir)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender :')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10, verbose_name='Marital Status :')),
                ('nationality', models.CharField(choices=[('malaysian', 'Malaysian'), ('foreigner', 'Foreigner')], max_length=15, verbose_name='Nationality :')),
                ('passport_ic', models.CharField(max_length=50, verbose_name='NRIC No :')),
                ('country_live_in', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True, verbose_name='Are you currently living in Malaysia?')),
                ('mobile_phone', models.CharField(max_length=50, verbose_name='Mobile Phone No :')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Contact No :')),
                ('medical_condition', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='Do you have medical condition to declare ? YES / NO')),
                ('medical_identify', models.CharField(blank=True, max_length=100, null=True, verbose_name='If yes, please identify :')),
                ('police_record', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='Do you have any police record ? YES / NO')),
                ('police_identify', models.CharField(blank=True, max_length=100, null=True, verbose_name='If yes, please identify case involved :')),
                ('spm_school_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='SPM School Name')),
                ('spm_certificate_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='SPM Level of Certification')),
                ('spm_graduated_year', models.DateField(blank=True, null=True, verbose_name='SPM Year of Graduated')),
                ('highest_education_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Highest Education School / College / University Name')),
                ('highest_certificate_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Highest Education Level of Certification')),
                ('highest_graduated_year', models.DateField(blank=True, null=True, verbose_name='Highest Education Year of Graduated')),
                ('professional_college_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Professional College / University Name')),
                ('professional_certificate_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Professional Level of Certification')),
                ('professional_graduated_year', models.DateField(blank=True, null=True, verbose_name='Professional Year of Graduated')),
                ('language', models.CharField(max_length=50, verbose_name='Language and dialects you speaks :')),
                ('total_working_experience', models.IntegerField(default=0, verbose_name='Total working experience :')),
                ('portfolio_url', models.URLField(max_length=1000)),
                ('portfolio_url_2', models.URLField(blank=True, max_length=1000, null=True)),
                ('portfolio_url_3', models.URLField(blank=True, max_length=1000, null=True)),
                ('employer_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employer (1) :')),
                ('job_title_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title :')),
                ('date_employed_1', models.DateField(blank=True, null=True, verbose_name='Date Employed :')),
                ('date_end_1', models.DateField(blank=True, null=True, verbose_name='Date End :')),
                ('employer_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employer (2) :')),
                ('job_title_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title :')),
                ('date_employed_2', models.DateField(blank=True, null=True, verbose_name='Date Employed :')),
                ('date_end_2', models.DateField(blank=True, null=True, verbose_name='Date End :')),
                ('employer_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employer (3) :')),
                ('job_title_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title :')),
                ('date_employed_3', models.DateField(blank=True, null=True, verbose_name='Date Employed :')),
                ('date_end_3', models.DateField(blank=True, null=True, verbose_name='Date End :')),
                ('available_joining_date', models.DateField(verbose_name='Available Joining Date :')),
                ('current_pay', models.IntegerField(verbose_name='Current Pay by Month :')),
                ('expected_pay', models.IntegerField(verbose_name='Expected Pay by Month :')),
                ('hobbies', models.CharField(max_length=50, verbose_name='Hobbies :')),
                ('other_information', models.CharField(max_length=100, verbose_name='Other information which help to consider your application :')),
                ('reference_name_1', models.CharField(max_length=50, verbose_name='Name')),
                ('reference_title_1', models.CharField(max_length=50, verbose_name='Title')),
                ('reference_company_1', models.CharField(max_length=50, verbose_name='Company')),
                ('reference_contact_1', models.CharField(max_length=50, verbose_name='Contact')),
                ('reference_email_1', models.EmailField(max_length=254, verbose_name='E-mail Address')),
                ('reference_name_2', models.CharField(max_length=50, verbose_name='Name')),
                ('reference_title_2', models.CharField(max_length=50, verbose_name='Title')),
                ('reference_company_2', models.CharField(max_length=50, verbose_name='Company')),
                ('reference_contact_2', models.CharField(max_length=50, verbose_name='Contact')),
                ('reference_email_2', models.EmailField(max_length=254, verbose_name='E-mail Address')),
                ('resume_copy', models.FileField(upload_to=oracle.models.JobApplication.upload_resume_dir, validators=[oracle.models.validate_file_extension])),
                ('passport_ic_copy', models.FileField(upload_to=oracle.models.JobApplication.upload_ic_dir, validators=[oracle.models.validate_file_extension])),
                ('highest_education_cert_copy', models.FileField(upload_to=oracle.models.JobApplication.upload_certificate_dir, validators=[oracle.models.validate_file_extension])),
                ('payslip_or_graduation_letter', models.FileField(upload_to=oracle.models.JobApplication.upload_payslip_dir, validators=[oracle.models.validate_file_extension])),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to=oracle.models.JobApplication.upload_recommendation_dir, validators=[oracle.models.validate_file_extension])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oracle.ApplicantList')),
                ('country_originated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oracle.CountryOriginated')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.Position', verbose_name='Position applied for :'),
        ),
        migrations.AddField(
            model_name='applicantlist',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.Position', verbose_name='Position applied for :'),
        ),
    ]
