# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantlist',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('offered', 'Offered')], default='new', max_length=30, verbose_name='Status :'),
        ),
    ]
